# Generated by Django 5.1.6 on 2025-04-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
